"""Direct OOXML PowerPoint generation; Microsoft PowerPoint is not required."""

from __future__ import annotations

import logging
import os
import tempfile
import uuid
from pathlib import Path

from pptx import Presentation
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Cm, Pt

from tiff_to_powerpoint.configuration import validate_generation_config
from tiff_to_powerpoint.converter import ConvertedImage, TiffConverter
from tiff_to_powerpoint.errors import ConfigurationError, TiffToPowerPointError
from tiff_to_powerpoint.layout import (
    ImageGeometry,
    LayoutItem,
    LayoutSettings,
    WIDESCREEN_HEIGHT_CM,
    WIDESCREEN_WIDTH_CM,
    calculate_slide_layout,
)
from tiff_to_powerpoint.models import AppConfig, GenerationResult, PairingResult, ProgressCallback, SlideGroup
from tiff_to_powerpoint.pairing import paginate_pairs


LOGGER = logging.getLogger(__name__)


def generate_presentation(
    pairing: PairingResult,
    config: AppConfig,
    progress: ProgressCallback | None = None,
) -> GenerationResult:
    """Convert sources, validate every slide, and atomically save a presentation."""

    validate_generation_config(config)
    if not pairing.pairs:
        raise ConfigurationError("There are no parsed image pairs to generate.")
    assert config.output_path is not None

    groups = paginate_pairs(pairing, config.max_columns_per_slide)
    source_paths = _unique_source_paths(pairing)
    total_steps = len(source_paths) + len(groups) + 1
    step = 0

    LOGGER.info("Generating %d slides from %d source TIFF files", len(groups), len(source_paths))
    with tempfile.TemporaryDirectory(prefix="tiff-to-pptx-") as temporary:
        converter = TiffConverter(Path(temporary))
        converted: dict[Path, ConvertedImage] = {}
        for path in source_paths:
            step += 1
            _notify(progress, step, total_steps, f"Converting {path.name}")
            converted[path.resolve()] = converter.convert(path)

        presentation = Presentation()
        presentation.slide_width = Cm(WIDESCREEN_WIDTH_CM)
        presentation.slide_height = Cm(WIDESCREEN_HEIGHT_CM)
        presentation.core_properties.title = "TIFF image presentation"
        presentation.core_properties.subject = "Generated by TIFF to PowerPoint"

        # A newly-created Presentation contains no slides, but this remains safe
        # for template changes in future.
        for group in groups:
            step += 1
            _notify(
                progress,
                step,
                total_steps,
                f"Building {group.primary} slide {group.page_number}/{group.total_pages}",
            )
            _add_slide(presentation, group, converted, config)

        output = config.output_path.resolve()
        temporary_output = output.with_name(f".{output.stem}-{uuid.uuid4().hex}.tmp.pptx")
        try:
            step += 1
            _notify(progress, step, total_steps, f"Saving {output.name}")
            presentation.save(temporary_output)
            os.replace(temporary_output, output)
        except (OSError, ValueError) as exc:
            LOGGER.exception("Failed to save presentation to %s", output)
            raise TiffToPowerPointError(f"Could not write PowerPoint '{output}': {exc}") from exc
        finally:
            temporary_output.unlink(missing_ok=True)

    LOGGER.info("Presentation saved to %s", output)
    return GenerationResult(output, len(groups), len(source_paths))


def _add_slide(
    presentation: Presentation,
    group: SlideGroup,
    converted: dict[Path, ConvertedImage],
    config: AppConfig,
) -> None:
    blank_layout = presentation.slide_layouts[6]
    slide = presentation.slides.add_slide(blank_layout)
    layout_items = tuple(_layout_item(pair, converted) for pair in group.items)
    settings = LayoutSettings(
        image_width_cm=config.image_width_cm,
        horizontal_gap_cm=config.horizontal_gap_cm,
        vertical_gap_cm=config.vertical_gap_cm,
        show_labels=config.show_labels,
    )
    layout = calculate_slide_layout(layout_items, settings)

    title = group.primary if group.total_pages == 1 else f"{group.primary} - {group.page_number}/{group.total_pages}"
    title_box = slide.shapes.add_textbox(
        Cm(layout.title_x_cm), Cm(layout.title_y_cm), Cm(layout.title_width_cm), Cm(layout.title_height_cm)
    )
    title_frame = title_box.text_frame
    title_frame.clear()
    title_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    paragraph = title_frame.paragraphs[0]
    paragraph.text = title
    paragraph.alignment = PP_ALIGN.LEFT
    paragraph.font.name = "Aptos Display"
    paragraph.font.size = Pt(22)
    paragraph.font.bold = True

    if config.show_labels:
        for column in layout.columns:
            label_box = slide.shapes.add_textbox(
                Cm(column.x_cm), Cm(column.label_y_cm), Cm(column.width_cm), Cm(settings.label_height_cm)
            )
            frame = label_box.text_frame
            frame.clear()
            frame.word_wrap = False
            frame.vertical_anchor = MSO_ANCHOR.MIDDLE
            label_paragraph = frame.paragraphs[0]
            label_paragraph.text = column.label
            label_paragraph.alignment = PP_ALIGN.CENTER
            label_paragraph.font.name = "Aptos"
            label_paragraph.font.size = Pt(10)

    for positioned in layout.images:
        pair = group.items[positioned.column_index]
        parsed = pair.normal_image if positioned.slot == "normal" else pair.volume_viewer_image
        assert parsed is not None
        png = converted[parsed.file_path.resolve()].png_path
        # Supplying only width asks python-pptx to preserve the PNG aspect ratio.
        slide.shapes.add_picture(str(png), Cm(positioned.x_cm), Cm(positioned.y_cm), width=Cm(positioned.width_cm))


def _layout_item(pair, converted: dict[Path, ConvertedImage]) -> LayoutItem:
    def geometry(parsed) -> ImageGeometry | None:
        if parsed is None:
            return None
        image = converted[parsed.file_path.resolve()]
        return ImageGeometry(parsed.file_name, image.pixel_width, image.pixel_height)

    return LayoutItem(pair.key.display_label, geometry(pair.normal_image), geometry(pair.volume_viewer_image))


def _unique_source_paths(pairing: PairingResult) -> tuple[Path, ...]:
    paths = {
        image.file_path
        for pair in pairing.pairs
        for image in (pair.normal_image, pair.volume_viewer_image)
        if image is not None
    }
    return tuple(sorted(paths, key=lambda path: str(path).casefold()))


def _notify(callback: ProgressCallback | None, current: int, total: int, message: str) -> None:
    LOGGER.debug("%s (%d/%d)", message, current, total)
    if callback is not None:
        callback(current, total, message)

